# Generated by Django 6.1 on 2026-09-03 10:00

from django.db import migrations, models


def backfill_status_from_is_active(apps, schema_editor):
    """Mark users who were deactivated before `status` existed as INACTIVE.

    The AddField above gives everyone the ACTIVE default, which would silently
    re-activate previously deactivated accounts. ``queryset.update`` is used on
    purpose: going through ``instance.save()`` would recompute ``is_active``
    from ``status`` and erase the very signal we are backfilling from.
    """
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_active=False).update(status=0)  # 0 = INACTIVE


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'suspended')], default=1, verbose_name='status'),
        ),
        migrations.RunPython(
            backfill_status_from_is_active,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
