# Generated by Django 6.1 on 2026-09-06 07:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTwoFactor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='created by id')),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='updated by id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='deleted by id')),
                ('user_id', models.UUIDField(db_index=True, unique=True, verbose_name='user id')),
                ('encrypted_secret', models.BinaryField(verbose_name='encrypted secret')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='is enabled')),
            ],
            options={
                'verbose_name': 'user two factor',
                'verbose_name_plural': 'user two factors',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='created by id'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='deleted by id'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='updated by id'),
        ),
    ]
