# Generated by Django 6.1 on 2026-09-17 05:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usertwofactor_user_created_at_user_created_by_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='created by id')),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='updated by id')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='deleted by id')),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='user id')),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='actor id')),
                ('action', models.CharField(choices=[('user_created', 'User dibuat'), ('user_updated', 'Profil user diperbarui'), ('user_deleted', 'User dinonaktifkan'), ('password_changed', 'Password diubah'), ('password_reset_requested', 'Link reset password dikirim'), ('password_reset_completed', 'Password di-reset melalui link'), ('user_activated', 'User diaktifkan'), ('user_suspended', 'User ditangguhkan'), ('user_deactivated', 'User dinonaktifkan'), ('group_assigned', 'Group ditambahkan'), ('group_unassigned', 'Group dihapus'), ('permission_granted', 'Permission diberikan'), ('permission_revoked', 'Permission dicabut'), ('two_factor_setup', 'Setup 2FA dimulai'), ('two_factor_enabled', '2FA diaktifkan'), ('two_factor_disabled', '2FA di-reset'), ('login_success', 'Login berhasil'), ('login_failed', 'Login gagal'), ('logout', 'Logout')], db_index=True, max_length=64, verbose_name='action')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
            ],
            options={
                'verbose_name': 'user activity',
                'verbose_name_plural': 'user activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
