# Generated by Django 6.1 on 2026-09-03 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('label', models.CharField(max_length=150, verbose_name='label')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='module')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('required_permission', models.CharField(blank=True, max_length=255, verbose_name='required permission')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'ordering': ['module', 'label'],
            },
        ),
        migrations.CreateModel(
            name='FeatureGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grantee_type', models.CharField(choices=[('group', 'Group'), ('user', 'User')], max_length=10, verbose_name='grantee type')),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='user id')),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=10, verbose_name='effect')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='access.feature', verbose_name='feature')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_grants', to='auth.group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'feature grant',
                'verbose_name_plural': 'feature grants',
                'ordering': ['feature__slug', 'grantee_type'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('grantee_type', 'group'), ('group__isnull', False), ('user_id__isnull', True)), models.Q(('grantee_type', 'user'), ('group__isnull', True), ('user_id__isnull', False)), _connector='OR'), name='access_grant_exactly_one_grantee'), models.UniqueConstraint(condition=models.Q(('grantee_type', 'group')), fields=('feature', 'group'), name='access_grant_unique_per_group'), models.UniqueConstraint(condition=models.Q(('grantee_type', 'user')), fields=('feature', 'user_id'), name='access_grant_unique_per_user')],
            },
        ),
    ]
