# Generated by Django 6.1 on 2026-09-05 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('label', models.CharField(max_length=150, verbose_name='label')),
                ('package', models.CharField(blank=True, max_length=200, verbose_name='package')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=250, unique=True, verbose_name='slug')),
                ('code', models.SlugField(max_length=100, verbose_name='code')),
                ('label', models.CharField(max_length=150, verbose_name='label')),
                ('category', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='category')),
                ('required_permission', models.CharField(blank=True, max_length=255, verbose_name='required permission')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='access.feature', verbose_name='feature')),
            ],
            options={
                'verbose_name': 'action',
                'verbose_name_plural': 'actions',
                'ordering': ['feature__slug', 'order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('feature', 'code'), name='access_action_unique_per_feature')],
            },
        ),
    ]
