# Generated by Django 6.1 on 2026-09-05 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_module_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='access.orgunit', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'org unit',
                'verbose_name_plural': 'org units',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnitMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='user id')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='access.orgunit', verbose_name='org unit')),
            ],
            options={
                'verbose_name': 'org unit membership',
                'verbose_name_plural': 'org unit memberships',
                'ordering': ['org_unit__slug'],
                'constraints': [models.UniqueConstraint(fields=('org_unit', 'user_id'), name='access_membership_unique_per_unit_user')],
            },
        ),
    ]
