# Generated by Django 6.1 on 2026-09-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_orgunit_orgunitmembership'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='featuregrant',
            name='access_grant_exactly_one_grantee',
        ),
        migrations.RemoveConstraint(
            model_name='featuregrant',
            name='access_grant_unique_per_group',
        ),
        migrations.RemoveConstraint(
            model_name='featuregrant',
            name='access_grant_unique_per_user',
        ),
        migrations.AddField(
            model_name='featuregrant',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='access.action', verbose_name='action'),
        ),
        migrations.AddField(
            model_name='featuregrant',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_grants', to='access.orgunit', verbose_name='org unit'),
        ),
        migrations.AlterField(
            model_name='featuregrant',
            name='grantee_type',
            field=models.CharField(choices=[('group', 'Group'), ('user', 'User'), ('org_unit', 'Org unit')], max_length=10, verbose_name='grantee type'),
        ),
        migrations.AddConstraint(
            model_name='featuregrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grantee_type', 'group'), ('group__isnull', False), ('org_unit__isnull', True), ('user_id__isnull', True)), models.Q(('grantee_type', 'user'), ('group__isnull', True), ('org_unit__isnull', True), ('user_id__isnull', False)), models.Q(('grantee_type', 'org_unit'), ('group__isnull', True), ('org_unit__isnull', False), ('user_id__isnull', True)), _connector='OR'), name='access_grant_exactly_one_grantee'),
        ),
        migrations.AddConstraint(
            model_name='featuregrant',
            constraint=models.UniqueConstraint(condition=models.Q(('action__isnull', True), ('grantee_type', 'group')), fields=('feature', 'group'), name='access_grant_unique_group_feature'),
        ),
        migrations.AddConstraint(
            model_name='featuregrant',
            constraint=models.UniqueConstraint(condition=models.Q(('action__isnull', False), ('grantee_type', 'group')), fields=('feature', 'action', 'group'), name='access_grant_unique_group_action'),
        ),
        migrations.AddConstraint(
            model_name='featuregrant',
            constraint=models.UniqueConstraint(condition=models.Q(('action__isnull', True), ('grantee_type', 'user')), fields=('feature', 'user_id'), name='access_grant_unique_user_feature'),
        ),
        migrations.AddConstraint(
            model_name='featuregrant',
            constraint=models.UniqueConstraint(condition=models.Q(('action__isnull', False), ('grantee_type', 'user')), fields=('feature', 'action', 'user_id'), name='access_grant_unique_user_action'),
        ),
        migrations.AddConstraint(
            model_name='featuregrant',
            constraint=models.UniqueConstraint(condition=models.Q(('action__isnull', True), ('grantee_type', 'org_unit')), fields=('feature', 'org_unit'), name='access_grant_unique_orgunit_feature'),
        ),
        migrations.AddConstraint(
            model_name='featuregrant',
            constraint=models.UniqueConstraint(condition=models.Q(('action__isnull', False), ('grantee_type', 'org_unit')), fields=('feature', 'action', 'org_unit'), name='access_grant_unique_orgunit_action'),
        ),
    ]
