# Generated by Django 6.1 on 2026-09-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_remove_featuregrant_access_grant_exactly_one_grantee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created_by_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='created by id'),
        ),
        migrations.AddField(
            model_name='action',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='action',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='deleted by id'),
        ),
        migrations.AddField(
            model_name='action',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='action',
            name='updated_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='updated by id'),
        ),
        migrations.AddField(
            model_name='feature',
            name='created_by_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='created by id'),
        ),
        migrations.AddField(
            model_name='feature',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='feature',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='deleted by id'),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='feature',
            name='updated_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='updated by id'),
        ),
        migrations.AddField(
            model_name='featuregrant',
            name='created_by_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='created by id'),
        ),
        migrations.AddField(
            model_name='featuregrant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='featuregrant',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='deleted by id'),
        ),
        migrations.AddField(
            model_name='featuregrant',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='featuregrant',
            name='updated_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='updated by id'),
        ),
        migrations.AddField(
            model_name='module',
            name='created_by_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='created by id'),
        ),
        migrations.AddField(
            model_name='module',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='module',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='deleted by id'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='updated by id'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='created_by_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='created by id'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='deleted by id'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='updated_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='updated by id'),
        ),
        migrations.AddField(
            model_name='orgunitmembership',
            name='created_by_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='created by id'),
        ),
        migrations.AddField(
            model_name='orgunitmembership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='orgunitmembership',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='deleted by id'),
        ),
        migrations.AddField(
            model_name='orgunitmembership',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='orgunitmembership',
            name='updated_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='updated by id'),
        ),
    ]
