# Generated by Django 6.1 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0005_action_created_by_id_action_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="registration_mode",
            field=models.CharField(
                choices=[
                    ("manual", "Manual dashboard"),
                    ("automatic", "Automatic scan"),
                ],
                default="manual",
                max_length=20,
                verbose_name="registration mode",
            ),
        ),
    ]
